Feature: workflow in git actions (#9)
* feat: initial Stylelint & config

* feat: add check Stylelint to git action & update php lint

* feat: logic for stylelint checker & add to husky

* feat: remove squizlabs/php_codesniffer from app & add to global

* feat: add custom rules by config phpcs.xml

* feat: add phpcs lint to Husky pre-commit

* feat: update eslint, phpcs, stylelint checker

* feat: update check message

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,3 +1,20 @@
-echo "❗=== Checking ESLint"
-# Check JS, TS format was valid with ESLint rules
-sh .husky/scripts/eslint-checker.sh
+# Run the script with an interactive terminal
+exec < /dev/tty
+
+# Keep color output in a Husky pre-commit hook 
+export FORCE_COLOR=1
+
+echo "💡=== Checking ESLint (.js,.ts,.jsx,.tsx)"
+sh .husky/workflows/eslint-checker.sh || PRE_COMMIT_FAILED=1
+
+echo "💡=== Checking Stylelint (.css,.scss)"
+sh .husky/workflows/stylelint-checker.sh || PRE_COMMIT_FAILED=1
+
+echo "💡=== Checking PHPCS (.php)"
+sh .husky/workflows/phpcs-checker.sh || PRE_COMMIT_FAILED=1
+
+# If any check failed, return a non-zero status (trigger pre-commit failure)
+if [[ $PRE_COMMIT_FAILED -eq 1 ]]; then
+  echo "❌❌❌ Check failed: One or more checks failed. Please fix the issues. ❌❌❌"
+  exit 1
+fi
